name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install composer requirements
        run: composer install
      - name: Run PHPUnit tests
        run: bin/phpunit
  build:
    runs-on: self-hosted
    needs:
      - tests
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PWD }}
      - name: Build image
        run: docker-compose build
      - name: Push image to docker hub
        run: docker-compose push
  deploy:
    runs-on: self-hosted
    needs:
      - build
    steps:
      - name: Deploy via deployer
        uses: musps/action-deployer-php@master
        with:
          args: deployer production -vvv
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}


